//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 10:33:21 PM EET 
//


package localhost._8080.user;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserDetails" type="{http://localhost:8080/user}UserDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "userDetails"
})
@XmlRootElement(name = "GetUserDetailsResponse")
public class GetUserDetailsResponse {

    @XmlElement(name = "UserDetails", required = true)
    protected UserDetails userDetails;

    /**
     * Gets the value of the userDetails property.
     *
     * @return possible object is
     * {@link UserDetails }
     */
    public UserDetails getUserDetails() {
        return userDetails;
    }

    /**
     * Sets the value of the userDetails property.
     *
     * @param value allowed object is
     *              {@link UserDetails }
     */
    public void setUserDetails(UserDetails value) {
        this.userDetails = value;
    }

}
