/* Login */
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

/* UserPolicy */
export const GET_USER_POLICY_START = 'GET_USER_POLICY_START';
export const GET_USER_POLICY_SUCCESS = 'GET_USER_POLICY_SUCCESS';
export const GET_USER_POLICY_FAIL = 'GET_USER_POLICY_FAIL';
export const SAVE_USER_POLICY_START = 'SAVE_USER_POLICY_START';
export const SAVE_USER_POLICY_SUCCESS = 'SAVE_USER_POLICY_SUCCESS';
export const SAVE_USER_POLICY_FAIL = 'SAVE_USER_POLICY_FAIL';

/* ComputerPolicy */
export const GET_COMPUTER_POLICY_START = 'GET_COMPUTER_POLICY_START';
export const GET_COMPUTER_POLICY_SUCCESS = 'GET_COMPUTER_POLICY_SUCCESS';
export const GET_COMPUTER_POLICY_FAIL = 'GET_COMPUTER_POLICY_FAIL';
export const SAVE_COMPUTER_POLICY_START = 'SAVE_COMPUTER_POLICY_START';
export const SAVE_COMPUTER_POLICY_SUCCESS = 'SAVE_COMPUTER_POLICY_SUCCESS';
export const SAVE_COMPUTER_POLICY_FAIL = 'SAVE_COMPUTER_POLICY_FAIL';
