/* Login */
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

/* UserPolicy */
export const GET_USER_POLICY_START = 'GET_USER_POLICY_START';
export const GET_USER_POLICY_SUCCESS = 'GET_USER_POLICY_SUCCESS';
export const GET_USER_POLICY_FAIL = 'GET_USER_POLICY_FAIL';
export const GET_USER_POLICIES_START = 'GET_USER_POLICIES_START';
export const GET_USER_POLICIES_SUCCESS = 'GET_USER_POLICIES_SUCCESS';
export const GET_USER_POLICIES_FAIL = 'GET_USER_POLICIES_FAIL';
export const UPDATE_USER_POLICY_START = 'UPDATE_USER_POLICY_START';
export const UPDATE_USER_POLICY_SUCCESS = 'UPDATE_USER_POLICY_SUCCESS';
export const UPDATE_USER_POLICY_FAIL = 'UPDATE_USER_POLICY_FAIL';
export const ADD_USER_POLICY_START = 'ADD_USER_POLICY_START';
export const ADD_USER_POLICY_SUCCESS = 'ADD_USER_POLICY_SUCCESS';
export const ADD_USER_POLICY_FAIL = 'ADD_USER_POLICY_FAIL';
export const DELETE_USER_POLICY_START = 'DELETE_USER_POLICY_START';
export const DELETE_USER_POLICY_SUCCESS = 'DELETE_USER_POLICY_SUCCESS';
export const DELETE_USER_POLICY_FAIL = 'DELETE_USER_POLICY_FAIL';

/* ComputerPolicy */
export const GET_COMPUTER_POLICY_START = 'GET_COMPUTER_POLICY_START';
export const GET_COMPUTER_POLICY_SUCCESS = 'GET_COMPUTER_POLICY_SUCCESS';
export const GET_COMPUTER_POLICY_FAIL = 'GET_COMPUTER_POLICY_FAIL';
export const SAVE_COMPUTER_POLICY_START = 'SAVE_COMPUTER_POLICY_START';
export const SAVE_COMPUTER_POLICY_SUCCESS = 'SAVE_COMPUTER_POLICY_SUCCESS';
export const SAVE_COMPUTER_POLICY_FAIL = 'SAVE_COMPUTER_POLICY_FAIL';

/* Applications */
export const GET_APPLICATIONS_START = 'GET_APPLICATIONS_START';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_FAIL = 'GET_APPLICATIONS_FAIL';
export const ADD_APPLICATION_START = 'ADD_APPLICATION_START';
export const ADD_APPLICATION_SUCCESS = 'ADD_APPLICATION_SUCCESS';
export const ADD_APPLICATION_FAIL = 'ADD_APPLICATION_FAIL';
export const DELETE_APPLICATION_START = 'DELETE_APPLICATION_START';
export const DELETE_APPLICATION_SUCCESS = 'DELETE_APPLICATION_SUCCESS';
export const DELETE_APPLICATION_FAIL = 'DELETE_APPLICATION_FAIL';
export const UPDATE_APPLICATION_START = 'UPDATE_APPLICATION_START';
export const UPDATE_APPLICATION_SUCCESS = 'UPDATE_APPLICATION_SUCCESS';
export const UPDATE_APPLICATION_FAIL = 'UPDATE_APPLICATION_FAIL';

/* Sites */
export const GET_SITES_START = 'GET_SITES_START';
export const GET_SITES_SUCCESS = 'GET_SITES_SUCCESS';
export const GET_SITES_FAIL = 'GET_SITES_FAIL';
export const ADD_SITE_START = 'ADD_SITE_START';
export const ADD_SITE_SUCCESS = 'ADD_SITE_SUCCESS';
export const ADD_SITE_FAIL = 'ADD_SITE_FAIL';
export const DELETE_SITE_START = 'DELETE_SITE_START';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const DELETE_SITE_FAIL = 'DELETE_SITE_FAIL';
export const UPDATE_SITE_START = 'UPDATE_SITE_START';
export const UPDATE_SITE_SUCCESS = 'UPDATE_SITE_SUCCESS';
export const UPDATE_SITE_FAIL = 'UPDATE_SITE_FAIL';

/* Users */
export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

/* Login Methods */
export const GET_LOGIN_METHODS_START = 'GET_LOGIN_METHODS_START';
export const GET_LOGIN_METHODS_SUCCESS = 'GET_LOGIN_METHODS_SUCCESS';
export const GET_LOGIN_METHODS_FAIL = 'GET_LOGIN_METHODS_FAIL';
